# Site settings
title: Guardian's Blog
description: 'There are many things that need to be done step by step'
url: 'http://www.guardian.cool'
baseurl: '/'
google_analytics: 'UA-87437901-1'
baidu-analyisis: 284ed0f8baccf88d6a37e9fcb8dca825 
#disqus_shortname: 'guardian-blog'
duoshuo_shortname: 'guardian'

author:
  name: 'F-Guardian'
  email: gd344040290@gmail.com
  twitter_username: F_Guardian
  facebook_username: guardian666
  github_username:  F-Guardian
  linkedin_username:  季骐-朱-807b91117

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:month/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
